[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[headers]
  [[headers]]
    for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "https://www.httnews.com"
