[build]
  command = "npm run build"
  publish = ".next"
  functions = "functions"
  base = "/"

[[plugins]]
  package = "netlify-plugin-cypress"
  

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    target = "experimental-serverless-trace"

